// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class RCarRentOrderInfoView
{
    public string fOrderId { get; set; }

    public int? fMemberId { get; set; }

    public string fName { get; set; }

    public string fCoupon_name { get; set; }

    public string fPayment { get; set; }

    public string fPaymentStatus { get; set; }

    public string fOrderStatus { get; set; }

    public string fOrderDate { get; set; }

    public decimal? fTotalPrice { get; set; }
}