// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class RCarInfoView
{
    public int fCarId { get; set; }

    public string fLicensePlateNum { get; set; }

    public string fModelName { get; set; }

    public string fImagePath { get; set; }

    public string fServicePoint { get; set; }

    public string fCompanyName { get; set; }

    public bool? fRentStatus { get; set; }
}