// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class RCarRentOrderDetailView
{
    public int fOrderDetailId { get; set; }

    public string fOrderId { get; set; }

    public string fLicensePlateNum { get; set; }

    public string fModelName { get; set; }

    public string fName { get; set; }

    public string fId { get; set; }

    public DateTime? fFromDateTime { get; set; }

    public string fServicePoint { get; set; }

    public DateTime? fRentDateTime { get; set; }

    public string fRentServicePoint { get; set; }

    public decimal? fPrice { get; set; }
}